name: ci

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
        compiler:
          - 'dmd-latest'
          - 'ldc-latest'
          - 'dmd-beta'
        packages:
          - 'utils'
          - 'semver'
          - 'sdlang'
          - 'path'
          - 'exception'
          - 'pkgdescription'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.compiler }}

    - name: Build CLI
      run: |
        dub build

    - name: Run semver
      working-directory: ${{ matrix.packages }}
      run: |
        dub test --compiler= ${{ matrix.compiler }}
