name: CI
on: [push, pull_request]

jobs:
  test:
    name: Dub Test
    strategy:
      matrix:
        os: [ubuntu-20.04]
        dc: [dmd-2.097.2, ldc-1.27.1]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1.1.0
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests
        run: ./runalltests.sh $DC library

      - name: Build binary
        run: dub build -q
